name: Get Playit Secret Key

on:
  workflow_dispatch:

jobs:
  get-key:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Run Playit
        run: |
          curl -fSL -o playit \
            "https://packages.playit.gg/install.sh"
          chmod +x playit
          ./playit > playit.log 2>&1 &
          sleep 15
          cat playit.log
